---
name: Collect Code Coverage

on:
  issue_comment:
    types: [created]

jobs:
  verify-allowed:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cc')
    runs-on: ubuntu-20.04
    steps:
    - name: Check Collaborator
      uses: actions/github-script@v6
      with:
        # We could wrap this in a try/catch and create a comment that they aren't allowed to run this action if we want
        script: |
          await github.rest.repos.checkCollaborator({
            owner: context.repo.owner,
            repo: context.repo.repo,
            username: context.payload.comment.user.login
          });
          console.log(context.payload.issue.pull_request);

  # run-tests:
  #   runs-on: ubuntu-20.04
  #   needs: verify-allowed
  #   strategy:
  #     matrix:
  #       ref: [one, two]
  #   steps:
  #   - name: Checkout repo
  #     run: 'echo ${{ matrix.ref }}'
