---
name: Collect Code Coverage

on:
  issue_comment:
    types: [created]

jobs:
  verify_allowed:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cc')
    runs-on: ubuntu-20.04
    outputs:
      pull_head: ${{ steps.pull_details.outputs.pull_head }}
      pull_base: ${{ steps.pull_details.outputs.pull_base }}
    steps:
    - name: Check Collaborator
      id: check_collaborator
      uses: actions/github-script@v6
      with:
        # We could wrap this in a try/catch and create a comment that they aren't allowed to run this action if we want
        script: |
          await github.rest.repos.checkCollaborator({
            owner: context.repo.owner,
            repo: context.repo.repo,
            username: context.payload.comment.user.login
          });

    - name: Get Pull Request Details
      id: pull_details
      uses: actions/github-script@v6
      with:
        script: |
          const pull = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          core.setOutput("pull_head", pull.data.head.ref);
          core.setOutput("pull_base", pull.data.base.ref);

  run_tests:
    runs-on: ubuntu-20.04
    needs: verify_allowed
    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.verify_allowed.outputs.pull_head }}
        path: './head'
    - name: Checkout base
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.verify_allowed.outputs.pull_base }}
        path: ./base
